version: 0.2

env:
  variables:
    # ECR repository URI (replace with your actual account ID & region)
    ECR_REGISTRY: 123456789012.dkr.ecr.us-east-1
    ECR_REPOSITORY: employee-service
    # ECS task definition family
    TASK_FAMILY: employee-task

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 19
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)
  pre_build:
    commands:
      - echo Building the Spring Boot JAR...
      - mvn clean package -DskipTests
      - echo Running unit tests...
      - mvn test -q
  build:
    commands:
      - echo Building Docker image and tagging with commit SHA...
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  post_build:
    commands:
      - echo Registering new Task Definition revision in ECS...
      # 1. Describe the existing task definition (we assume a family named $TASK_FAMILY)
      - TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY --query "taskDefinition{family:family,containerDefinitions:containerDefinitions}" --output json)
      # 2. Replace the image URI in containerDefinitions[0]
      - UPDATED_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" '.containerDefinitions[0].image = $IMAGE')
      # 3. Write the updated JSON to a file and register a new revision
      - echo "$UPDATED_TASK_DEF" > new-task-def.json
      - aws ecs register-task-definition --cli-input-json file://new-task-def.json --family $TASK_FAMILY
      # 4. Retrieve the newly registered task definition ARN
      - NEW_TASK_DEF_ARN=$(aws ecs list-task-definitions --family-prefix $TASK_FAMILY --sort DESC --max-items 1 --query "taskDefinitionArns[0]" --output text)
      # 5. Update the ECS service to use the new task definition
      - aws ecs update-service --cluster employee-cluster --service employee-service --task-definition $NEW_TASK_DEF_ARN
artifacts:
  files:
    - new-task-def.json